print('Exception2')

# NameError
# 4 + spam * 3

print('program exit')
