print('Exception3')

# TypeError
'2' + 2

print('program exit')
